substitutions:
    devicename: fluval-proxy-charlies
    devicemac: 44:A6:E5:68:C1:42
    address: 192.168.2.16
    ble_client_id: charlies_client
    fluval_ble_led_id: charlies

esphome:
  name: $devicename
  project:
    name: aquariums.$devicename
    version: "1.0"

esp32:
  #  board: esp32doit-devkit-v1
  #framework:
  #  type: arduino
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: b9LP2QBS+AG/FJx3UJrB9DH+40mWsE1pmXgHgdoeXR0=

ota:
  password: "aaaaaaaa"

wifi:
  ssid: "all_the_smart_things"
  password: "deadbeef"
  use_address: $address
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #    ssid: "Fluval Fallback Hotspot"
  #    password: "aaaaaaaa"

    #dashboard_import:
    #  package_import_url: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

    #captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: $devicemac
    id: $ble_client_id

time:
  - platform: homeassistant
    id: ha_time


external_components:
  - source: github://mrzottel/esphome@fluval_ble_led
    components: [ fluval_ble_led ]


fluval_ble_led:
  - ble_client_id: $ble_client_id
    time_id: ha_time
    number_of_channels: 4
    id: $fluval_ble_led_id

button:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "MANUAL"
    name: "Switch to manual"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "AUTO"
    name: "Switch to auto"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "PRO"
    name: "Switch to pro"

switch:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    name: "light"

text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    name: "mode"

sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 1
    zero_if_off: true
    name: "Green"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 2
    zero_if_off: true
    name: "Cold white"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 3
    zero_if_off: true
    name: "Blue"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 4
    zero_if_off: true
    name: "Rose"

number:
- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Green"
  channel: 1
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Cold White"
  channel: 2
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Blue"
  channel: 3
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Rose"
  channel: 4
  zero_if_off: true
