substitutions:
    devicename: fluval-proxy-breeder
    devicemac: 44:A6:E5:70:00:34
#    address: 192.168.2.27
    ble_client_id: breeder_client
    fluval_ble_led_id: breeder

esphome:
  name: $devicename
  project:
    name: aquariums.$devicename
    version: "1.0"

esp32:
  #  board: esp32doit-devkit-v1
  #framework:
  #  type: arduino
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
    platform: esphome
    password: "aaaaaaaa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: $address
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #    ssid: "Fluval Fallback Hotspot"
  #    password: "aaaaaaaa"

    #dashboard_import:
    #  package_import_url: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

    #captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: $devicemac
    id: $ble_client_id

time:
  - platform: homeassistant
    id: ha_time


external_components:
  - source: github://mrzottel/esphome@fluval_ble_led
    components: [ fluval_ble_led ]


fluval_ble_led:
  - ble_client_id: $ble_client_id
    time_id: ha_time
    number_of_channels: 4
    id: $fluval_ble_led_id

button:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "MANUAL"
    name: "Switch to manual"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "AUTO"
    name: "Switch to auto"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    mode: "PRO"
    name: "Switch to pro"

switch:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    name: "light"
  - platform: ble_client
    ble_client_id: $ble_client_id
    name: "Toggle $fluval_ble_led_id"


text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    name: "mode"
  - platform: version
    name: ESPHome Version

sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 1
    zero_if_off: true
    name: "Ch1: Rose"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 2
    zero_if_off: true
    name: "Ch2: Green"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 3
    zero_if_off: true
    name: "Ch3: Blue"

  - platform: fluval_ble_led
    fluval_ble_led_id: $fluval_ble_led_id
    channel: 4
    zero_if_off: true
    name: "Ch4: White"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
      

number:
- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Ch1: Rose"
  channel: 1
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Ch2: Green"
  channel: 2
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Ch3: Blue"
  channel: 3
  zero_if_off: true

- platform: fluval_ble_led
  fluval_ble_led_id: $fluval_ble_led_id
  name: "Ch4: White"
  channel: 4
  zero_if_off: true



