substitutions:
  name: kauf-plug-dehumidifier
  friendly_name: Dehumidifier Plug
packages:
  Kauf.PLF12: github://KaufHA/PLF12/kauf-plf12.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
dashboard_import:
  package_import_url: github://ashmandias/esphome/kauf-plug/${name}.yaml@main
api:
  encryption:
    key: !secret api_encryption_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
