substitutions:
  name: kauf-plug-sump1
  friendly_name: Sump Plug 1
packages:
  Kauf.PLF12: github://KaufHA/PLF12/kauf-plf12.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  #  encryption:
  #  #key: 2QReAcuKy138dxKeeykPTfb+Yqux2W5jOX8q7zryCGU=
  #  key: !secret api_encryption_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""


text_sensor:
  - platform: version
    name: ESPHome Version

